name: Publish website from Cpanel
on: 
 push:
  branches:
    - Samuel
jobs:
  FTP-Deploy-Action:
   name: FTP-Deploy-Action
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
   
